---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cluster-whalesay
  namespace: argo-workflows
spec:
  # run daily at 2am
  schedule: "*/15 * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: whalesay-cluster
      clusterScope: true
