---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: whalesay-ns
  namespace: argo-workflows
spec:
  event:
    selector: payload.message != "" && discriminator == "whalesay-ns"
  submit:
    workflowTemplateRef:
      name: whalesay-ns
      namespace: argo-workflows
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message
