---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: whalesay-hello-world-template
spec:

  entrypoint: whalesay

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message       # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: docker.io/docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
