---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $.Values.global.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  to:
    kind: Service
    name: {{ $.Values.global.name }}-argo-workflows-server
    weight: 100
  port:
    targetPort: 2746
  tls:
    termination: edge
  wildcardPolicy: None
