---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.dex.fullnameOverride }}
  namespace: {{ $.Values.dex.namespace | default $.Values.global.namespace }}
spec:
  port:
    targetPort: 5556
  to:
    kind: Service
    name: {{ $.Values.dex.fullnameOverride }}
  tls:
    termination: edge
  wildcardPolicy: None
