{
 "title": "[DEPRECATED] ARGO Metrics",
 "description": "This dashboard is used to monitor the metrics related to \r\n ARGO workflow controller metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "argo_pod_missing",
   "type": "stat",
   "description": "Pods were not seen. E.g. by being deleted by Kubernetes. You should only see this under high load.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "argo_pod_missing", "legendFormat": "argo_pod_missing" }
   ]
  },
  {
   "title": "argo_workflows_count",
   "type": "stat",
   "description": "Number of workflow in each phase",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{status=\"Pending\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "argo_workflows_count{status=\"Running\"}",
     "legendFormat": "running"
    },
    {
     "expr": "argo_workflows_count{status=\"Skipped\"}",
     "legendFormat": "skipped"
    },
    {
     "expr": "argo_workflows_count{status=\"Succeeded\"}",
     "legendFormat": "succeeded"
    }
   ]
  },
  {
   "title": "argo_workflows_count",
   "type": "stat",
   "description": "Number of workflow in each phase",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{status=\"Error\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "argo_workflows_count",
   "type": "stat",
   "description": "Number of workflow in each phase",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{status=\"Failed\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "argo_workflows_error_count",
   "type": "stat",
   "description": "A count of certain errors incurred by the controller",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_error_count{cause=\"CronWorkflowSubmissionError\"}",
     "legendFormat": "CronWorkflowSubmissionError"
    }
   ]
  },
  {
   "title": "argo_workflows_error_count",
   "type": "stat",
   "description": "A count of certain errors incurred by the controller",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_error_count{cause=\"OperationPanic\"}",
     "legendFormat": "OperationPanic"
    }
   ]
  },
  {
   "title": "argo_workflows_k8s_request_total",
   "type": "stat",
   "description": "Number of API requests sent to the Kubernetes API.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_k8s_request_total",
     "legendFormat": "argo_workflows_k8s_request_total"
    }
   ]
  },
  {
   "title": "argo_workflows_operation_duration_seconds_bucket",
   "type": "heatmap",
   "description": "A histogram of durations of operations.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"+Inf\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"0.25\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"0.5\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"0.75\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"1\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"1.25\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"1.5\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"1.75\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"2\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"2.5\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{le=\"3\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "argo_workflows_operation_duration_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_duration_seconds_count",
     "legendFormat": "argo_workflows_operation_duration_seconds_count"
    }
   ]
  },
  {
   "title": "argo_workflows_operation_duration_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_operation_duration_seconds_sum",
     "legendFormat": "argo_workflows_operation_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "argo_workflows_pods_count",
   "type": "stat",
   "description": "It is possible for a workflow to start, but no pods be running (e.g. cluster is too busy to run them). This metric sheds light on actual work being done.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "argo_workflows_pods_count", "legendFormat": "argo_workflows_pods_count" }
   ]
  },
  {
   "title": "argo_workflows_queue_adds_count",
   "type": "stat",
   "description": "The number of additions to the queue of workflows or cron workflows.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "argo_workflows_queue_adds_count{queue_name=\"cron_wf_queue\"}",
     "legendFormat": "cron_wf_queue"
    },
    {
     "expr": "argo_workflows_queue_adds_count{queue_name=\"pod_queue\"}",
     "legendFormat": "pod_queue"
    },
    {
     "expr": "argo_workflows_queue_adds_count{queue_name=\"wf_cron_queue\"}",
     "legendFormat": "wf_cron_queue"
    },
    {
     "expr": "argo_workflows_queue_adds_count{queue_name=\"workflow_queue\"}",
     "legendFormat": "workflow_queue"
    },
    {
     "expr": "argo_workflows_queue_adds_count{queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "workflow_ttl_queue"
    }
   ]
  },
  {
   "title": "argo_workflows_queue_depth_count",
   "type": "stat",
   "description": "The depth of the queue of workflows or cron workflows to be processed by the controller.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{queue_name=\"cron_wf_queue\"}",
     "legendFormat": "cron_wf_queue"
    },
    {
     "expr": "argo_workflows_queue_depth_count{queue_name=\"pod_queue\"}",
     "legendFormat": "pod_queue"
    },
    {
     "expr": "argo_workflows_queue_depth_count{queue_name=\"wf_cron_queue\"}",
     "legendFormat": "wf_cron_queue"
    },
    {
     "expr": "argo_workflows_queue_depth_count{queue_name=\"workflow_queue\"}",
     "legendFormat": "workflow_queue"
    },
    {
     "expr": "argo_workflows_queue_depth_count{queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "workflow_ttl_queue"
    }
   ]
  },
  {
   "title": "argo_workflows_queue_latency_bucket",
   "type": "heatmap",
   "description": "The time workflows or cron workflows spend in the queue waiting to be processed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"+Inf\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"+Inf\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"+Inf\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"+Inf\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"+Inf\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"1\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"1\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"1\",queue_name=\"wf_cron_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"1\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"1\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"180\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"180\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"180\",queue_name=\"wf_cron_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"180\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"180\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"20\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"20\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"20\",queue_name=\"wf_cron_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"20\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"20\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"5\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"5\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"5\",queue_name=\"wf_cron_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"5\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"5\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"60\",queue_name=\"cron_wf_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"60\",queue_name=\"pod_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"60\",queue_name=\"wf_cron_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"60\",queue_name=\"workflow_queue\"}",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "argo_workflows_queue_latency_bucket{le=\"60\",queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "argo_workflows_queue_latency_count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_queue_latency_count{queue_name=\"cron_wf_queue\"}",
     "legendFormat": "cron_wf_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_count{queue_name=\"pod_queue\"}",
     "legendFormat": "pod_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_count{queue_name=\"wf_cron_queue\"}",
     "legendFormat": "wf_cron_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_count{queue_name=\"workflow_queue\"}",
     "legendFormat": "workflow_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_count{queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "workflow_ttl_queue"
    }
   ]
  },
  {
   "title": "argo_workflows_queue_latency_sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_latency_sum{queue_name=\"cron_wf_queue\"}",
     "legendFormat": "cron_wf_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_sum{queue_name=\"pod_queue\"}",
     "legendFormat": "pod_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_sum{queue_name=\"wf_cron_queue\"}",
     "legendFormat": "wf_cron_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_sum{queue_name=\"workflow_queue\"}",
     "legendFormat": "workflow_queue"
    },
    {
     "expr": "argo_workflows_queue_latency_sum{queue_name=\"workflow_ttl_queue\"}",
     "legendFormat": "workflow_ttl_queue"
    }
   ]
  },
  {
   "title": "argo_workflows_workers_busy",
   "type": "stat",
   "description": "The number of workers that are busy.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "argo_workflows_workers_busy", "legendFormat": "argo_workflows_workers_busy" }
   ]
  },
  {
   "title": "argo_workflows_workflow_condition",
   "type": "stat",
   "description": "The number of workflow with different conditions. This will tell you the number of workflows with running pods.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "argo_workflows_workflow_condition",
     "legendFormat": "argo_workflows_workflow_condition"
    }
   ]
  },
  {
   "title": "argo_workflows_workflows_processed_count",
   "type": "stat",
   "description": "A count of all Workflow updates processed by the controller.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "argo_workflows_workflows_processed_count",
     "legendFormat": "argo_workflows_workflows_processed_count"
    }
   ]
  }
 ]
}