{
 "title": "Dex Metrics",
 "description": "Metrics from Dex server compatible with multi prometheus origins like Thanos.",
 "tags": [
  "argo",
  "dex"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "Kubernetes Cluster",
    "query": {
     "query": "label_values(argo_workflows_count,prometheus)"
    }
   },
   {
    "name": "ns",
    "label": "WF Controller Namespace",
    "query": {
     "query": "label_values(argo_workflows_count{prometheus=~\"^$dc$\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Dex Pod",
    "query": {
     "query": "label_values(http_requests_total{prometheus=~\"^$dc$\",namespace=~\"$ns$\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dex Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP requests count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, handler, code) (increase(http_requests_total{prometheus=~\"^$dc$\",namespace=\"$ns\"}[2m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{handler}}: {{code}}"
    }
   ]
  },
  {
   "title": "OpenShift Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=~\"$ns\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~\"$pod\",namespace=~\"$ns\"}) BY (pod, namespace)",
     "legendFormat": "Request {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~\"$pod\",namespace=~\"$ns\"}) BY (pod, namespace)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource='memory',pod=~\"$pod\",namespace=~\"$ns\"}) BY (pod, namespace)",
     "legendFormat": "Request {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='memory',pod=~\"$pod\",namespace=~\"$ns\"}) BY (pod, namespace)",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",namespace=~\"$ns\",container='',}) BY (pod, namespace)",
     "legendFormat": "Used {{pod}}"
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"container_network_receive_bytes_total\",namespace=~\"$ns\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Rx {{pod}}"
    },
    {
     "expr": "- rate({__name__=~\"container_network_transmit_bytes_total\",namespace=~\"$ns\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Tx {{pod}}"
    }
   ]
  }
 ]
}